config/routes.rb
Rails.application.routes.draw do
  resources :convalidacion_items
  resources :relacions
  resources :estudiantes
  resources :personas
  resources :convalidacions
  resources :asignaturas
  resources :pensums
  resources :carreras
  resources :universidads
  devise_for :users
  get 'pages/info'
  root to: redirect('/convalidacions')
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asignatura.rb
class Asignatura < ApplicationRecord
  belongs_to :pensum
  has_many :relacions
end

app/models/carrera.rb
class Carrera < ApplicationRecord
  belongs_to :universidad
  has_many :pensums
  has_many :asignaturas, through: :pensums
  has_many :estudiantes
end

app/models/convalidacion.rb
class Convalidacion < ApplicationRecord
  belongs_to :estudiante, optional: true
  belongs_to :universidad, optional: true
  has_many :convalidacion_items
  has_many :asignaturas, through: :convalidacion_items
  has_many :relacions, through: :convalidacion_items

  accepts_nested_attributes_for :estudiante                                
  accepts_nested_attributes_for :convalidacion_items
                                

  validates :universidad_home_id, presence: true
  validates :universidad_procedencia_id, presence:true
  validate :total_credit_values_valid?
  
  validates_associated :convalidacion_items

  def total_credit_values_valid?
    
    if total_creditos_home <= total_creditos_procedencia
      return true
    else 
      errors.add(:total_creditos_home, "- El total de creditos convalidables debe ser mayor al total de creditos convalidados")
      return false
    end
  end
end

app/models/convalidacion_item.rb
class ConvalidacionItem < ApplicationRecord
  belongs_to :convalidacion, optional: true
  has_many :relacions
  has_many :asignaturas

  validates :asignatura_local_nombre, :asignatura_local_clave, :asignatura_local_creditos, presence: true
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
  belongs_to :persona, optional: true
  has_many :carreras
  has_many :asignaturas, through: :carrera
  has_many :convalidacions

  validates :nombres, presence: true
  validates :apellidos, presence: true
  validates :matricula, presence: true
  
end

app/models/idea.rb
class Idea < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/models/pensum.rb
class Pensum < ApplicationRecord
  belongs_to :carrera
  has_many :asignaturas
end

app/models/persona.rb
class Persona < ApplicationRecord
  
end

app/models/relacion.rb
class Relacion < ApplicationRecord
  has_many :asignaturas
  has_many :convalidacions
  
  # validate presence of required fields
  validates :asignatura_home_id, presence: true
  validates :asignatura_a_procedencia_id, presence: true
  validate :credit_values_valid?, if: [:asignatura_a_procedencia_id, :asignatura_home_id]
  
  # validates :universidad_local_id, presence: true
  # validates :carrera_local_id, presence: true
  # validates :pensum_local_id, presence: true
  # validates :universidad_procedencia_id, presence: true
  # validates :carrera_procedencia_id, presence: true
  # validates :pensum_procedencia_id, presence: true
  # validates :asignatura_a_procedencia_creditos_id, presence: true, numericality: true, length: {minimum: 1, maximum: 15}
  # validates :asignatura_b_procedencia_creditos_id, numericality: true, length: {minimum: 1, maximum: 15}
   

  def credit_values_valid?
    creditos_asignatura_a = Asignatura.find(asignatura_a_procedencia_id).creditos
    creditos_asignatura_home = Asignatura.find(asignatura_home_id).creditos
    if asignatura_b_procedencia_id == nil
      if creditos_asignatura_a >= creditos_asignatura_home - 1  
        return true
      else
        errors.add(:asignatura_a_procedencia_id, "Creditos no son suficientes para relacionar.")
        return false
      end
    else if asignatura_b_procedencia_id != nil
      creditos_asignatura_b = Asignatura.find(asignatura_b_procedencia_id).creditos
      if creditos_asignatura_a + creditos_asignatura_b >= creditos_asignatura_home
        return true
      else
        errors.add(:asignatura_a_procedencia_id, "Creditos no son suficientes para relacionar.")
        return false
      end
    else
      errors.add(:asignatura_a_procedencia_id, "Creditos no son suficientes para relacionar.")
      return false
      end 
    end   
  end
end

app/models/universidad.rb
class Universidad < ApplicationRecord
  has_many :carreras
  has_many :pensums, through: :carreras
  has_many :asignaturas, through: :pensums
  has_many :estudiantes, through: :carreras
  has_many :convalidacions

  mount_uploader :logo, LogoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/carreras_controller.rb
class CarrerasController < ApplicationController
  before_action :set_carrera, only: [:show, :edit, :update, :destroy]

  # GET /carreras
  # GET /carreras.json
  def index
    @search = Carrera.search(params[:q])
    @carreras = @search.result
  end

  # GET /carreras/1
  # GET /carreras/1.json
  def show
  end

  # GET /carreras/new
  def new
    @carrera = Carrera.new
  end

  # GET /carreras/1/edit
  def edit
  end

  # POST /carreras
  # POST /carreras.json
  def create
    @carrera = Carrera.new(carrera_params)

    respond_to do |format|
      if @carrera.save
        format.html { redirect_to @carrera, notice: 'Carrera creada con éxito.' }
        format.json { render :show, status: :created, location: @carrera }
      else
        format.html { render :new }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carreras/1
  # PATCH/PUT /carreras/1.json
  def update
    respond_to do |format|
      if @carrera.update(carrera_params)
        format.html { redirect_to @carrera, notice: 'Carrera editada con éxito.' }
        format.json { render :show, status: :ok, location: @carrera }
      else
        format.html { render :edit }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carreras/1
  # DELETE /carreras/1.json
  def destroy
    @carrera.destroy
    respond_to do |format|
      format.html { redirect_to carreras_url, notice: 'Carrera eliminada con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrera
      @carrera = Carrera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrera_params
      params.require(:carrera).permit(:nombre, :universidad_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pensums_helper.rb
module PensumsHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/relacions_helper.rb
module RelacionsHelper
end

app/helpers/universidads_helper.rb
module UniversidadsHelper
end

app/views/carreras/_form.html.erb
<%= form_with(model: carrera, local: true) do |form| %>
  <% if carrera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carrera.errors.count, "errores") %> encontrados por lo que no se pudo guardar ésta carrera:</h2>

      <ul>
      <% carrera.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :universidad_id %>
    <%= collection_select( :carrera, :universidad_id, Universidad.all, :id, :nombre, {}, {:multiple => false, :class => "form-control"})   %>
  </div>

  <br>
      
  <div class="actions">
    <%= form.submit "Procesar Carrera", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/carreras/edit.html.erb
<h1>Editing Carrera</h1>

<%= render 'form', carrera: @carrera %>

<%= link_to 'Ver', @carrera %> |
<%= link_to 'Volver', carreras_path %>

app/views/carreras/index.html.erb
<h1>Carreras</h1>

<br>

<%= search_form_for @search do |f| %>
  <div class="form-inline">
    <div class='field'>
      <%= f.label :nombre_cont, "Nombre contiene:" %>
      <%= f.text_field :nombre_cont, class: "form-control" %>
      <input class="btn btn-primary" type="submit" value="Buscar">
    </div>
  </div>
<% end %>

<br>

<table id='carreras_table_id' class='table table-hover'>
  <thead id='carreras_table_head_id'>
    <tr>
      <th><%= sort_link @search, :nombre, "Nombre" %></th>
      <th><%= sort_link @search, :universidad_id, "Universidad" %></th>      
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody id='carreras_table_body_id'>
    <% @carreras.each do |carrera| %>
      <tr>
        <td><%= carrera.nombre %></td>
        <td><%= carrera.universidad.descripcion %> (<%= carrera.universidad.nombre %>)</td>
        <td><%= link_to 'Ver', carrera %></td>
        <td><%= link_to 'Editar', edit_carrera_path(carrera) %></td>
        <td><%= link_to 'Eliminar', carrera, method: :delete, data: { confirm: '¿Está Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Carrera', new_carrera_path %>

app/views/carreras/new.html.erb
<h1>Nueva Carrera</h1>

<%= render 'form', carrera: @carrera %>

<%= link_to 'Volver', carreras_path %>

app/views/carreras/show.html.erb
<br><br>

<p>
  <strong>Nombre:</strong>
  <%= @carrera.nombre %>
</p>

<p>
  <strong>Universidad:</strong>
  <%= @carrera.universidad.nombre %>
</p>

<%= link_to 'Editar', edit_carrera_path(@carrera) %> |
<%= link_to 'Volver', carreras_path %>

<div id='info_tables_pensums_id'>
  <h3>Pensums</h3>

  <div>
    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Universidad</th>
          <th>Carrera</th>
          <th>Nombre</th>
          <th>Date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @carrera.pensums.each do |pensum| %>
          <tr>
            <td><%= pensum.carrera.universidad.nombre %></td>
            <td><%= pensum.carrera.nombre %></td>
            <td><%= pensum.nombre %></td>
            <td><%= pensum.date %></td>
            <td><%= link_to 'Ver', pensum %></td>
            <td><%= link_to 'Editar', edit_pensum_path(pensum) %></td>
            <td><%= link_to 'Eliminar', pensum, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>

  <div id='info_tables_asignaturas_id'>
    <h3>Asignaturas</h3>

    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Clave</th>
          <th>Nombre</th>
          <th>Creditos</th>
          <th>Universidad</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @carrera.asignaturas.each do |asignatura| %>
          <tr>
            <td><%= asignatura.clave %></td>
            <td><%= asignatura.nombre %></td>
            <td><%= asignatura.creditos %></td>
            <td><%= asignatura.pensum.carrera.universidad.descripcion %> (<%= asignatura.pensum.carrera.universidad.nombre %>)</td>
            <td><%= link_to 'Ver', asignatura %></td>
            <td><%= link_to 'Editar', edit_asignatura_path(asignatura) %></td>
            <td><%= link_to 'Eliminar', asignatura, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>