config/routes.rb
Rails.application.routes.draw do
  resources :convalidacion_items
  resources :relacions
  resources :estudiantes
  resources :personas
  resources :convalidacions
  resources :asignaturas
  resources :pensums
  resources :carreras
  resources :universidads
  devise_for :users
  get 'pages/info'
  root to: redirect('/convalidacions')
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/convalidacion.rb
class Convalidacion < ApplicationRecord
  belongs_to :estudiante, optional: true
  belongs_to :universidad, optional: true
  has_many :convalidacion_items
  has_many :asignaturas, through: :convalidacion_items
  has_many :relacions, through: :convalidacion_items

  accepts_nested_attributes_for :estudiante                                
  accepts_nested_attributes_for :convalidacion_items
                                

  validates :universidad_home_id, presence: true
  validates :universidad_procedencia_id, presence:true
  validate :total_credit_values_valid?
  
  validates_associated :convalidacion_items

  def total_credit_values_valid?
    
    if total_creditos_home <= total_creditos_procedencia
      return true
    else 
      errors.add(:total_creditos_home, "- El total de creditos convalidables debe ser mayor al total de creditos convalidados")
      return false
    end
  end
end

app/controllers/convalidacions_controller.rb
class ConvalidacionsController < ApplicationController
  before_action :set_convalidacion, only: [:show, :edit, :update, :destroy]

  # GET /convalidacions
  # GET /convalidacions.json
  def index
    @search = Convalidacion.search(params[:q])
    @convalidacions = @search.result
    
  end

  # GET /convalidacions/1
  # GET /convalidacions/1.json
  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'convalidacions/convalidacionpdf', pdf: 'Convalidacionpdf' }
    end
  end

  # GET /convalidacions/new
  def new
    @convalidacion = Convalidacion.new
    @convalidacion.build_estudiante
    @convalidacion.convalidacion_items.new
  end

  # GET /convalidacions/1/edit
  def edit
  end

  # POST /convalidacions
  # POST /convalidacions.json
  def create
    @convalidacion = Convalidacion.new(convalidacion_params)

    # byebug
    respond_to do |format|
      if @convalidacion.save
        @estudiante = @convalidacion.estudiante
        @convalidacion.convalidacion_items.each do |item|
          byebug
          @convalidacion_item = item
        end
        # byebug
        format.html { redirect_to @convalidacion, notice: 'Convalidación creada con éxito.' }
        format.json { render :show, status: :created, location: @convalidacion }
      else
        format.html { render :new }
        format.json { render json: @convalidacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /convalidacions/1
  # PATCH/PUT /convalidacions/1.json
  def update
    respond_to do |format|
      if @convalidacion.update(convalidacion_params)
        format.html { redirect_to @convalidacion, notice: 'Convalidación actualizada con éxito.' }
        format.json { render :show, status: :ok, location: @convalidacion }
      else
        format.html { render :edit }
        format.json { render json: @convalidacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /convalidacions/1
  # DELETE /convalidacions/1.json
  def destroy
    @convalidacion.destroy
    respond_to do |format|
      format.html { redirect_to convalidacions_url, notice: 'Convalidación eliminada con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_convalidacion
      @convalidacion = Convalidacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def convalidacion_params
      params.require(:convalidacion).permit(:universidad_home_id, :universidad_procedencia_id, :carrera_home_id, :carrera_procedencia_id, :total_creditos_home, :total_creditos_procedencia, :estudiante_id, estudiante_attributes: [:id, :nombres, :apellidos, :matricula],\
                                            convalidacion_items_attributes: [:id, :convalidacion_id, :asignatura_procedencia_clave, :asignatura_procedencia_nombre,\
                                            :asignatura_procedencia_calificacion, :asignatura_procedencia_creditos, :asignatura_local_clave, :asignatura_local_nombre,\
                                            :asignatura_local_creditos])
    end

end

app/helpers/convalidacions_helper.rb
module ConvalidacionsHelper
end

app/views/convalidacions/_form.html.erb
<%= form_with(model: convalidacion, local: true) do |form| %>
  <% if convalidacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(convalidacion.errors.count, "errores") %> encontrados por lo que no se pudo guardar ésta convalidación:</h2>

      <ul>
      <% convalidacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Información General</h3>
    </div>
    <div class="panel-body">
      <form>        
        <div class="form_group">
          <div class="page-header">
            <h3><small>Información de Estudiante</small></h3>
          </div>
          <div class="form-inline">      
            <%= form.fields_for :estudiante do |e| %> 
              <%= e.label :nombres , class:"form-control" %>
              <%= e.text_field :nombres , class:"form-control" %>

              <%= e.label :apellidos , class:"form-control" %>
              <%= e.text_field :apellidos , class:"form-control" %>

              <%= e.label :matricula , class:"form-control" %>
              <%= e.text_field :matricula , class:"form-control" %>
            <% end %>
          </div>
        </div>
        

        <div class="form-inline">
          <div class="form-group">
            <div class="page-header">
              <h3><small>Información local</small></h3>
            </div>

            <div class="form-inline">
              <%= form.label :universidad_home_id, "Universidad Local" %>
              <%= form.collection_select :universidad_home_id, Universidad.all, :id, :nombre, {:include_blank => true}, {:class => "form-control"} %>
              <div class="form-group">
                <%= form.label :carrera_home_id, "Carrera Local" %>
                <%= form.grouped_collection_select :carrera_home_id, Universidad.order(:nombre), :carreras, :nombre, :id,  :nombre , {:include_blank => true}, {:class => "form-control"} %>
              </div>
              <div class="form-group">
                <%= form.label :pensum_home_id, "Pensum Local" %>
                <%= form.grouped_collection_select :pensum_home_id, Carrera.order(:nombre), :pensums, :nombre, :id,  :nombre , {:include_blank => true}, {:class => "form-control"} %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="page-header">
              <h3><small>Información de procedencia</small></h3>
            </div>

            <div class="form-inline">
              <div class="form-group">
                <%= form.label :universidad_procedencia_id, "Universidad de Procedencia" %>
                <%= form.collection_select :universidad_procedencia_id, Universidad.order(:nombre), :id, :nombre, {:include_blank => true}, {:class => "form-control"} %>
              </div>
              <div class="form-group">
                <%= form.label :carrera_procedencia_id, "Carrera de Procedencia" %>
                <%= form.grouped_collection_select :carrera_procedencia_id, Universidad.order(:nombre), :carreras, :nombre, :id,  :nombre , {:include_blank => true}, {:class => "form-control"} %>
              </div>
              <div class="form-group">
                <%= form.label :pensum_procedencia_id, "Pensum de Procedencia" %>
                <%= form.grouped_collection_select :pensum_procedencia_id, Carrera.order(:nombre), :pensums, :nombre, :id, :nombre, {:multiple => true, :include_blank => true}, {:class => "form-control"} %>
              </div>
            </div>
          </div>
        </div>
        
        <div class="page-header">
          <h3><small>Seleccione las asignaturas de procedencia a convalidar</small></h3>
        </div>

        <div class="form-inline">
          <div class="form-group">
            <label for="asignaturas_home_choose">Asignaturas Locales</label>
            <div class="form-inline">
              <div class="field">
                <select style="width: 400px; height: 250px" multiple class="list-group" id="asignaturas_home_choose">
                </select>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label for="asignaturas_procedencia_choose">Asignaturas de procedencia</label>
            <div class="form-inline">
              <div class="field">
                <select style="width: 400px; height: 250px" multiple class="list-group" id="asignaturas_procedencia_choose">
                </select>
              </div>
            </div>
          </div>
        </div>

        <input type="Action" id="convalidar_seleccion_button_id" name="convalidar_seleccion_button" class="btn btn-primary" value="Convalidar Selección" >
        
        <br><br> 
        <%= form.fields_for :convalidacion_items do | item | %>
          <div id="hidden_items_fields_div_id">
          
          </div>
        <% end %>

        <div class="form-group">
          <h3>Reporte de Convalidación</h3>   

          <table id='asignaturas_convalidables_table_id' class="table table-hover">
              <thead>
                  <tr>
                      <th><%=  %>Clave</th>
                      <th><%=  %>Asig. Convalidables</th>
                      <th><%=  %>Calificacion</th>
                      <th><%=  %>CR</th>
                      <th><%=  %>Clave</th>
                      <th><%=  %>Asig. Convalidadas</th>
                      <th><%=  %>CR</th>                                      
                  </tr>
              </thead>
                      
              <tbody id='asignaturas_convalidables_table_tbody_id'>
              
              </tbody>
          </table>

          <div class="form-inline">
            <%= form.label :total_creditos_procedencia, 'Total de Creditos convalidables' , class:"form-control"  %>
            <%= form.text_field :total_creditos_procedencia , class:"form-control", :readonly => true %>  
            <%= form.label :total_creditos_home,  'Total de Creditos convalidados' , class:"form-control" %>
            <%= form.text_field :total_creditos_home , class:"form-control", :readonly => true %>   
          <div>
        </div>

        <br>
        
        <div class="actions">
          <input type="submit" name="commit" value="Crear Convalidación" class="btn btn-success" data-disable-with="Procesando...">          
        </div>

      </form>
    </div>
  </div>

<% end %>

app/views/convalidacions/convalidacionpdf.pdf.erb
<!DOCTYPE html>
<html>
    <head>  <meta http-equiv=Content-Type content="text/html; charset=UTF-8">
        <style type="text/css">
            <!--
            /* divs */
            div.footer {bottom: 15%; width: 100%}
            div.general_info{display: inline-block;} 
            div.header {text-align: center;}
            div.info_section {border: 2px solid black; margin-top: 40px}            
            div.note {text-align: justify; margin: auto; width: 80%}
            div.note span {font-size: 18px}
            div.note span em {font-weight: bold; text-decoration: underline}
            
            
            /* tables */            
            table.info {border: 1px solid black;border-collapse: collapse; font-size:10.0px;width:100%;}
            table.info th {border: 1px solid black;font-size:18.0px;font-weight:bold;font-style:normal}
            table.info td {border: 1px solid black;font-style:normal;font-size:18.0px}
            table.info td.align-center {text-align: center}
            table.signatures {table-layout: auto; width: 100%}
            table.signatures th {font-weight: bold}
            table.signatures td {text-align: center; font-weight: bold; font-size: 18px}
            table.signatures td.signatures_name {text-align: center; font-weight: bold; text-decoration: underline; font-size: 20px}

            /* texts */
            h3 {font-family:Times,serif;font-weight:bold;text-decoration: none; margin: 2px}
            h3.title {margin: 15px; color: rgb(22, 25, 228)}            
            h4 {font-family:Times,serif;font-weight:bold;text-decoration: none; margin: 5px}
            span {font-family:Times,serif;font-weight:bold;text-decoration: none; margin: 2px}
            .inline-item {display: inline;}
            .align-right{float: right;}
            .bold {font-weight:bold}
            .boldcenter {font-weight:bold; text-align: center}

            /* footer */
            footer{margin-top: 250px; float: center}


            -->
        </style>
        <script type="text/javascript" src="351d80d0-af13-11e8-b59b-0cc47a792c0a_id_351d80d0-af13-11e8-b59b-0cc47a792c0a_files/wz_jsgraphics.js"></script>
    </head>

    <body>
        <div class="header">
            <h3>UNIVERSIDAD ABIERTA PARA ADULTOS</h3> 
            <h3>UAPA</h3> 
            <h3>SANTIAGO DE LOS CABALLEROS, REP.DOM.</h3>
            <h3 class="title">CONVALIDACION DE ASIGNATURA(S)</h3>
        </div>

        <div class="info_section">
            <div>
                <div class='inline-item'>
                    <span class='align-left'>MATRICULA:   <%= @convalidacion.estudiante.matricula %></span>
                    <span class='align-right' Style="padding-right: 15px">FECHA DE SOLICITUD: <%= @convalidacion.created_at.strftime("%d-%m-%Y") %></span>
                </div>
                <h4>NOMBRE (S):   <%= @convalidacion.estudiante.nombres %></h4>
                <h4>APELLIDOS (S):   <%= @convalidacion.estudiante.apellidos %></h4>
                <h4>CARRERA:   <%= Carrera.find(@convalidacion.carrera_home_id).nombre %></h4> 
                <br>                
                <h4>UNIVERSIDAD DE PROCEDENCIA:   <%= Universidad.find(@convalidacion.universidad_procedencia_id).descripcion %> (<%= Universidad.find(@convalidacion.universidad_procedencia_id).nombre %>)</h4>
                <h4>CARRERA DE PROCEDENCIA:   <%= Carrera.find(@convalidacion.carrera_procedencia_id).nombre %></h4>
            </div>

            
        </div>
        <br>
        
        <div>
            <table class="info">
                <thead>
                    <tr>
                        <th>Clave</th>
                        <th>Asig. Convalidables</th>
                        <th>Calif.</th>
                        <th>CR</th>
                        <th>Clave</th>
                        <th>Asig. Convalidadas</th>
                        <th>CR</th>                        
                    </tr>
                </thead>

                <tbody>
                    <%- ConvalidacionItem.where(convalidacion_id: @convalidacion.id).each do | item | %>
                        <tr>
                            <td class="align-center"><%= item.asignatura_procedencia_clave %></td>
                            <td><%= item.asignatura_procedencia_nombre %></td>
                            <td class="align-center"><%= item.asignatura_procedencia_calificacion %></td>
                            <td class="align-center"><%= item.asignatura_procedencia_creditos %></td>
                            <td class="align-center"><%= item.asignatura_local_clave %></td>
                            <td><%= item.asignatura_local_nombre %></td>
                            <td class="align-center"><%= item.asignatura_local_creditos %></td>
                        </tr>                                         
                    <% end %>
                    <tr>
                        <td></td>
                        <td class="bold">Total Créditos Convalidables:</td>
                        <td></td>
                        <td class="boldcenter"><%= @convalidacion.total_creditos_procedencia %></td>
                        <td></td>
                        <td class="bold">Total Créditos Convalidados:</td>
                        <td class="boldcenter"><%= @convalidacion.total_creditos_home %></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <br><br>
        <footer> 
            <div >
                <table class="signatures">
                    <thead>
                        <th></th>
                        <th class="signatures">_________________________________</th>
                        <th class="signatures">_________________________________</th>
                        <th></th>
                    
                    </thead>

                    <tbody>
                        <tr>                        
                            <td></td>
                            <td class="signatures_name">Dra. Reyna Hiraldo</td>
                            <td class="signatures_name">Alexandra Ventura M.A.</td>
                            <td></td>
                        </tr>
                        <tr>                        
                            <td></td>
                            <td class="signatures">Director(a) Escuela de Ingeniería y Tecnología</td>
                            <td class="signatures">Director(a) de Registro</td>
                            <td></td>
                        </tr>
                    </tbody>            
                </table>
                <br><br>
                <div class="note">
                    <span><em>NOTA:</em> Este formulario es válido si está debidamente firmado y sellado por las autoridades académicas autorizadas.</span>
                </div>           
        </footer>
    </body>
</html>

app/views/convalidacions/edit.html.erb
<h1>Editar Convalidación</h1>

<%= render 'form', convalidacion: @convalidacion %>

<%= link_to 'Ver', @convalidacion %> |
<%= link_to 'Volver', convalidacions_path %>

app/views/convalidacions/index.html.erb
<h1>Convalidaciones Realizadas</h1>

<br>

<%= search_form_for @search do |f| %>
  <div class="form-inline">
    <div class='field'>
      <%= f.label :estudiante_nombres_cont, "Nombre contiene:" %>
      <%= f.text_field :estudiante_nombres_cont, class: "form-control" %>
      <input class="btn btn-primary" type="submit" value="Buscar">
    </div>
  </div>
<% end %>

<table class='table table-hover'> 
  <thead>
    <tr>
      <th><%= sort_link @search, :estudiante_id, "Estudiante"%></th>
      <th>Matrícula</th>
      <th>Universidad de procedencia</th>
      <th>Fecha</th>
      <th colspan="2">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @convalidacions.each do |convalidacion| %>
      <tr>
        <td><%= Estudiante.find(convalidacion.estudiante_id).nombres %> <%= Estudiante.find(convalidacion.estudiante_id).apellidos %></td>
        <td><%= Estudiante.find(convalidacion.estudiante_id).matricula %></td>
        <td><%= Universidad.find(convalidacion.universidad_procedencia_id).descripcion %></td>
        <td><%= convalidacion.created_at.strftime("%d-%m-%Y") %></td>
        <td><%= link_to 'Ver', convalidacion %></td>
        <td><%= link_to 'Eliminar', convalidacion, method: :delete, data: { confirm: '¿Está Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Convalidación', new_convalidacion_path %>

app/views/convalidacions/new.html.erb
<h1>Nueva Convalidación</h1>

<%= render 'form', convalidacion: @convalidacion %>

<%= link_to 'Volver', convalidacions_path %>

app/views/convalidacions/show.html.erb
<br><br>

<h4><span class="glyphicon glyphicon-print" aria-hidden="false" id='imprimir_convalidacion'>  <%= link_to 'Imprimir Convalidación', convalidacion_path(format: :pdf) %></span></h4>

<br>

<p>
  <strong>Estudiante:</strong>
  <%= Estudiante.find(@convalidacion.estudiante_id).nombres %> <%= Estudiante.find(@convalidacion.estudiante_id).apellidos %>
  (<%= Estudiante.find(@convalidacion.estudiante_id).matricula %>) <%= link_to 'Editar Estudiante', edit_estudiante_path(@convalidacion.estudiante_id), {:class => "btn btn-primary btn-sm"} %>
</p>

<p>
  <strong>Universidad de procedencia:</strong>
  <%= Universidad.find(@convalidacion.universidad_procedencia_id).descripcion %> (<%= Universidad.find(@convalidacion.universidad_procedencia_id).nombre %>)
</p>
<p>
  <strong>Fecha de realizacion:</strong>
  <%= @convalidacion.created_at %>
</p>

<div id='info_tables_convalidacion_items_id'>
  <h3>Detalles de la Convalidación</h3>  
    <table class='table table-hover'>   
      <thead>
          <tr>
              <th>Clave</th>
              <th>Asig. Convalidables</th>
              <th>Calificacion</th>
              <th>CR</th>
              <th>Clave</th>
              <th>Asig. Convalidadas</th>
              <th>CR</th>                        
          </tr>
      </thead>

      <tbody>
          <%- ConvalidacionItem.where(convalidacion_id: @convalidacion.id).each do | item | %>
            <tr> 
                <td><%= item.asignatura_procedencia_clave %></td>
                <td><%= item.asignatura_procedencia_nombre %></td>
                <td><%= item.asignatura_procedencia_calificacion %></td>
                <td><%= item.asignatura_procedencia_creditos %></td>
                <td><%= item.asignatura_local_clave %></td>
                <td><%= item.asignatura_local_nombre %></td>
                <td><%= item.asignatura_local_creditos %></td>
            </tr>
          <% end %>
      </tbody>
    </table>    

<%= link_to 'Editar detalles', edit_convalidacion_path(@convalidacion) %> |
<%= link_to 'Volver', convalidacions_path %>