config/routes.rb
Rails.application.routes.draw do
  resources :convalidacion_items
  resources :relacions
  resources :estudiantes
  resources :personas
  resources :convalidacions
  resources :asignaturas
  resources :pensums
  resources :carreras
  resources :universidads
  devise_for :users
  get 'pages/info'
  root to: redirect('/convalidacions')
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asignatura.rb
class Asignatura < ApplicationRecord
  belongs_to :pensum
  has_many :relacions
end

app/models/carrera.rb
class Carrera < ApplicationRecord
  belongs_to :universidad
  has_many :pensums
  has_many :asignaturas, through: :pensums
  has_many :estudiantes
end

app/models/convalidacion.rb
class Convalidacion < ApplicationRecord
  belongs_to :estudiante, optional: true
  belongs_to :universidad, optional: true
  has_many :convalidacion_items
  has_many :asignaturas, through: :convalidacion_items
  has_many :relacions, through: :convalidacion_items

  accepts_nested_attributes_for :estudiante                                
  accepts_nested_attributes_for :convalidacion_items
                                

  validates :universidad_home_id, presence: true
  validates :universidad_procedencia_id, presence:true
  validate :total_credit_values_valid?
  
  validates_associated :convalidacion_items

  def total_credit_values_valid?
    
    if total_creditos_home <= total_creditos_procedencia
      return true
    else 
      errors.add(:total_creditos_home, "- El total de creditos convalidables debe ser mayor al total de creditos convalidados")
      return false
    end
  end
end

app/models/convalidacion_item.rb
class ConvalidacionItem < ApplicationRecord
  belongs_to :convalidacion, optional: true
  has_many :relacions
  has_many :asignaturas

  validates :asignatura_local_nombre, :asignatura_local_clave, :asignatura_local_creditos, presence: true
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
  belongs_to :persona, optional: true
  has_many :carreras
  has_many :asignaturas, through: :carrera
  has_many :convalidacions

  validates :nombres, presence: true
  validates :apellidos, presence: true
  validates :matricula, presence: true
  
end

app/models/idea.rb
class Idea < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/models/pensum.rb
class Pensum < ApplicationRecord
  belongs_to :carrera
  has_many :asignaturas
end

app/models/persona.rb
class Persona < ApplicationRecord
  
end

app/models/relacion.rb
class Relacion < ApplicationRecord
  has_many :asignaturas
  has_many :convalidacions
  
  # validate presence of required fields
  validates :asignatura_home_id, presence: true
  validates :asignatura_a_procedencia_id, presence: true
  validate :credit_values_valid?, if: [:asignatura_a_procedencia_id, :asignatura_home_id]
  
  # validates :universidad_local_id, presence: true
  # validates :carrera_local_id, presence: true
  # validates :pensum_local_id, presence: true
  # validates :universidad_procedencia_id, presence: true
  # validates :carrera_procedencia_id, presence: true
  # validates :pensum_procedencia_id, presence: true
  # validates :asignatura_a_procedencia_creditos_id, presence: true, numericality: true, length: {minimum: 1, maximum: 15}
  # validates :asignatura_b_procedencia_creditos_id, numericality: true, length: {minimum: 1, maximum: 15}
   

  def credit_values_valid?
    creditos_asignatura_a = Asignatura.find(asignatura_a_procedencia_id).creditos
    creditos_asignatura_home = Asignatura.find(asignatura_home_id).creditos
    if asignatura_b_procedencia_id == nil
      if creditos_asignatura_a >= creditos_asignatura_home - 1  
        return true
      else
        errors.add(:asignatura_a_procedencia_id, "Creditos no son suficientes para relacionar.")
        return false
      end
    else if asignatura_b_procedencia_id != nil
      creditos_asignatura_b = Asignatura.find(asignatura_b_procedencia_id).creditos
      if creditos_asignatura_a + creditos_asignatura_b >= creditos_asignatura_home
        return true
      else
        errors.add(:asignatura_a_procedencia_id, "Creditos no son suficientes para relacionar.")
        return false
      end
    else
      errors.add(:asignatura_a_procedencia_id, "Creditos no son suficientes para relacionar.")
      return false
      end 
    end   
  end
end

app/models/universidad.rb
class Universidad < ApplicationRecord
  has_many :carreras
  has_many :pensums, through: :carreras
  has_many :asignaturas, through: :pensums
  has_many :estudiantes, through: :carreras
  has_many :convalidacions

  mount_uploader :logo, LogoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/universidads_controller.rb
class UniversidadsController < ApplicationController
  before_action :set_universidad, only: [:show, :edit, :update, :destroy]

  # GET /universidads
  # GET /universidads.json
  def index
    @search = Universidad.search(params[:q])
    @universidads = @search.result
  end

  # GET /universidads/1
  # GET /universidads/1.json
  def show
    
  end

  # GET /universidads/new
  def new
    @universidad = Universidad.new
  end

  # GET /universidads/1/edit
  def edit
  end

  # POST /universidads
  # POST /universidads.json
  def create
    @universidad = Universidad.new(universidad_params)

    respond_to do |format|
      if @universidad.save
        format.html { redirect_to @universidad, notice: 'Universidad creada con éxito.' }
        format.json { render :show, status: :created, location: @universidad }
      else
        format.html { render :new }
        format.json { render json: @universidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universidads/1
  # PATCH/PUT /universidads/1.json
  def update
    respond_to do |format|
      if @universidad.update(universidad_params)
        format.html { redirect_to @universidad, notice: 'Universidad editada con éxito.' }
        format.json { render :show, status: :ok, location: @universidad }
      else
        format.html { render :edit }
        format.json { render json: @universidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universidads/1
  # DELETE /universidads/1.json
  def destroy
    @universidad.destroy
    respond_to do |format|
      format.html { redirect_to universidads_url, notice: 'Universidad eliminada con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_universidad
      @universidad = Universidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def universidad_params
      params.require(:universidad).permit(:nombre, :descripcion, :logo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pensums_helper.rb
module PensumsHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/relacions_helper.rb
module RelacionsHelper
end

app/helpers/universidads_helper.rb
module UniversidadsHelper
end

app/views/universidads/_form.html.erb
<%= form_with(model: universidad, local: true) do |form| %>
  <% if universidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(universidad.errors.count, "errores") %> impidió que se guardara esta universidad:</h2>

      <ul>
      <% universidad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.file_field :logo, id: :universidad_logo, class: "form-control-file" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Procesar Universidad", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/universidads/edit.html.erb
<h1>Editar Universidad</h1>

<%= render 'form', universidad: @universidad %>

<%= link_to 'Ver', @universidad %> |
<%= link_to 'Volver', universidads_path %>

app/views/universidads/index.html.erb
<h1>Universidades</h1>

<br>

<%= search_form_for @search do |f| %>
  <div class="form-inline">
    <div class='field'>
      <%= f.label :nombre_cont, "Nombre contiene:" %>
      <%= f.text_field :nombre_cont, class: "form-control" %>
      <input class="btn btn-primary" type="submit" value="Buscar">
    </div>
  </div>
<% end %>

<br>

<table id='universidad_table' class="table table-hover" style="width:100%">
  <thead>
    <tr>
      <th><%= sort_link @search, :id, "ID" %></th>
      <th><%= sort_link @search, :nombre, "Nombre" %></th>
      <th><%= sort_link @search, :descripcion, "Descripcion" %></th>
      <th>Logo</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @universidads.each do |universidad| %>
      <tr>
        <th scope="row"><%= universidad.id %>
        <td><%= universidad.nombre %></td>
        <td><%= universidad.descripcion %></td>
        <td><%= image_tag universidad.logo_url, class: '.img-responsive .center-block img-rounded', style:'width:50px' if universidad.logo.present? %>
        <td><%= link_to 'Ver', universidad %></td>
        <td><%= link_to 'Editar', edit_universidad_path(universidad) %></td>
        <td><%= link_to 'Eliminar', universidad, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Universidad', new_universidad_path %>

app/views/universidads/new.html.erb
<h1>Nueva Universidad</h1>

<%= render 'form', universidad: @universidad %>

<%= link_to 'Volver', universidads_path %>

app/views/universidads/show.html.erb
<br><br>
<p>
  <strong>Nombre:</strong>
  <%= @universidad.nombre %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @universidad.descripcion %>
</p>

<p>
  <strong>Logo:</strong>
  <%= image_tag(@universidad.logo_url, width: 150) if @universidad.logo.present? %>
</p>

<%= link_to 'Editar', edit_universidad_path(@universidad) %> |
<%= link_to 'Volver', universidads_path %>

<div id='info_tables_id'>

  <div id='info_tables_carreras_id'>
    <h3>Carreras</h3>

    <table id='carreras_table_id' class='table table-hover'>
      <thead id='carreras_table_head_id'>
        <tr>
          <th>Nombre</th>
          <th>Universidad</th>
          <th>Pensums</th>
          <th colspan="3">Acciones</th>
        </tr>
      </thead>

      <tbody id='carreras_table_body_id'>
        <% @universidad.carreras.each do |carrera| %>
          <tr>
            <td><%= carrera.nombre %></td>
            <td><%= carrera.universidad.nombre %></td>
            <td><button type="button" id='ver_pensums_button_id' class="btn btn-primary">Ver Pensums</button></td>
            <td><%= link_to 'Ver', carrera %></td>
            <td><%= link_to 'Editar', edit_carrera_path(carrera) %></td>
            <td><%= link_to 'Eliminar', carrera, method: :delete, data: { confirm: 'Estás seguro?'} %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div id='info_tables_pensums_id'>
    <h3>Pensums</h3>

    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Universidad</th>
          <th>Carrera</th>
          <th>Nombre</th>
          <th>Date</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @universidad.pensums.each do |pensum| %>
          <tr>
            <td><%= pensum.carrera.universidad.nombre %></td>
            <td><%= pensum.carrera.nombre %></td>
            <td><%= pensum.nombre %></td>
            <td><%= pensum.date %></td>
            <td><%= link_to 'Ver', pensum %></td>
            <td><%= link_to 'Editar', edit_pensum_path(pensum) %></td>
            <td><%= link_to 'Eliminar', pensum, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>

  <div id='info_tables_asignaturas_id'>
    <h3>Asignaturas</h3>

    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Clave</th>
          <th>Nombre</th>
          <th>Creditos</th>
          <th>Universidad</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @universidad.asignaturas.each do |asignatura| %>
          <tr>
            <td><%= asignatura.clave %></td>
            <td><%= asignatura.nombre %></td>
            <td><%= asignatura.creditos %></td>
            <td><%= asignatura.pensum.carrera.universidad.descripcion %> (<%= asignatura.pensum.carrera.universidad.nombre %>)</td>
            <td><%= link_to 'Ver', asignatura %></td>
            <td><%= link_to 'Editar', edit_asignatura_path(asignatura) %></td>
            <td><%= link_to 'Eliminar', asignatura, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
  </div>

</div>