config/routes.rb
Rails.application.routes.draw do
  resources :convalidacion_items
  resources :relacions
  resources :estudiantes
  resources :personas
  resources :convalidacions
  resources :asignaturas
  resources :pensums
  resources :carreras
  resources :universidads
  devise_for :users
  get 'pages/info'
  root to: redirect('/convalidacions')
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asignatura.rb
class Asignatura < ApplicationRecord
  belongs_to :pensum
  has_many :relacions
end

app/models/carrera.rb
class Carrera < ApplicationRecord
  belongs_to :universidad
  has_many :pensums
  has_many :asignaturas, through: :pensums
  has_many :estudiantes
end

app/models/convalidacion.rb
class Convalidacion < ApplicationRecord
  belongs_to :estudiante, optional: true
  belongs_to :universidad, optional: true
  has_many :convalidacion_items
  has_many :asignaturas, through: :convalidacion_items
  has_many :relacions, through: :convalidacion_items

  accepts_nested_attributes_for :estudiante                                
  accepts_nested_attributes_for :convalidacion_items
                                

  validates :universidad_home_id, presence: true
  validates :universidad_procedencia_id, presence:true
  validate :total_credit_values_valid?
  
  validates_associated :convalidacion_items

  def total_credit_values_valid?
    
    if total_creditos_home <= total_creditos_procedencia
      return true
    else 
      errors.add(:total_creditos_home, "- El total de creditos convalidables debe ser mayor al total de creditos convalidados")
      return false
    end
  end
end

app/models/convalidacion_item.rb
class ConvalidacionItem < ApplicationRecord
  belongs_to :convalidacion, optional: true
  has_many :relacions
  has_many :asignaturas

  validates :asignatura_local_nombre, :asignatura_local_clave, :asignatura_local_creditos, presence: true
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
  belongs_to :persona, optional: true
  has_many :carreras
  has_many :asignaturas, through: :carrera
  has_many :convalidacions

  validates :nombres, presence: true
  validates :apellidos, presence: true
  validates :matricula, presence: true
  
end

app/models/idea.rb
class Idea < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/models/pensum.rb
class Pensum < ApplicationRecord
  belongs_to :carrera
  has_many :asignaturas
end

app/models/persona.rb
class Persona < ApplicationRecord
  
end

app/models/relacion.rb
class Relacion < ApplicationRecord
  has_many :asignaturas
  has_many :convalidacions
  
  # validate presence of required fields
  validates :asignatura_home_id, presence: true
  validates :asignatura_a_procedencia_id, presence: true
  validate :credit_values_valid?, if: [:asignatura_a_procedencia_id, :asignatura_home_id]
  
  # validates :universidad_local_id, presence: true
  # validates :carrera_local_id, presence: true
  # validates :pensum_local_id, presence: true
  # validates :universidad_procedencia_id, presence: true
  # validates :carrera_procedencia_id, presence: true
  # validates :pensum_procedencia_id, presence: true
  # validates :asignatura_a_procedencia_creditos_id, presence: true, numericality: true, length: {minimum: 1, maximum: 15}
  # validates :asignatura_b_procedencia_creditos_id, numericality: true, length: {minimum: 1, maximum: 15}
   

  def credit_values_valid?
    creditos_asignatura_a = Asignatura.find(asignatura_a_procedencia_id).creditos
    creditos_asignatura_home = Asignatura.find(asignatura_home_id).creditos
    if asignatura_b_procedencia_id == nil
      if creditos_asignatura_a >= creditos_asignatura_home - 1  
        return true
      else
        errors.add(:asignatura_a_procedencia_id, "Creditos no son suficientes para relacionar.")
        return false
      end
    else if asignatura_b_procedencia_id != nil
      creditos_asignatura_b = Asignatura.find(asignatura_b_procedencia_id).creditos
      if creditos_asignatura_a + creditos_asignatura_b >= creditos_asignatura_home
        return true
      else
        errors.add(:asignatura_a_procedencia_id, "Creditos no son suficientes para relacionar.")
        return false
      end
    else
      errors.add(:asignatura_a_procedencia_id, "Creditos no son suficientes para relacionar.")
      return false
      end 
    end   
  end
end

app/models/universidad.rb
class Universidad < ApplicationRecord
  has_many :carreras
  has_many :pensums, through: :carreras
  has_many :asignaturas, through: :pensums
  has_many :estudiantes, through: :carreras
  has_many :convalidacions

  mount_uploader :logo, LogoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/pensums_controller.rb
class PensumsController < ApplicationController
  before_action :set_pensum, only: [:show, :edit, :update, :destroy]

  # GET /pensums
  # GET /pensums.json
  def index
    @search = Pensum.search(params[:q])
    @pensums = @search.result
  end

  # GET /pensums/1
  # GET /pensums/1.json
  def show
  end

  # GET /pensums/new
  def new
    @pensum = Pensum.new
  end

  # GET /pensums/1/edit
  def edit
  end

  # POST /pensums
  # POST /pensums.json
  def create
    @pensum = Pensum.new(pensum_params)

    respond_to do |format|
      if @pensum.save
        format.html { redirect_to @pensum, notice: 'Pensum creado con éxito.' }
        format.json { render :show, status: :created, location: @pensum }
      else
        format.html { render :new }
        format.json { render json: @pensum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pensums/1
  # PATCH/PUT /pensums/1.json
  def update
    respond_to do |format|
      if @pensum.update(pensum_params)
        format.html { redirect_to @pensum, notice: 'Pensum actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @pensum }
      else
        format.html { render :edit }
        format.json { render json: @pensum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pensums/1
  # DELETE /pensums/1.json
  def destroy
    @pensum.destroy
    respond_to do |format|
      format.html { redirect_to pensums_url, notice: 'Pensum eliminado con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pensum
      @pensum = Pensum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pensum_params
      params.require(:pensum).permit(:nombre, :date, :carrera_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pensums_helper.rb
module PensumsHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/relacions_helper.rb
module RelacionsHelper
end

app/helpers/universidads_helper.rb
module UniversidadsHelper
end

app/views/pensums/_form.html.erb
<%= form_with(model: pensum, local: true) do |form| %>
  <% if pensum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pensum.errors.count, "errores") %> encontrados por lo que no se pudo guardar éste pensum:</h2>

      <ul>
      <% pensum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: "form-control" %>
  </div>
  <br>
        
  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, :class => "form-control" %>
  </div>
  <br>

  <div class="field">
    <%= form.label :universidad_id %>
    <%= form.collection_select :universidad_id, Universidad.order(:nombre), :id, :nombre, {:include_blank => true}, {:class => "form-control"}  %>
  </div>
  <br>

  <div class="field">
    <%= form.label :carrera_id %>
    <%= form.grouped_collection_select :carrera_id, Universidad.order(:nombre), :carreras, :nombre, :id,  :nombre , {:include_blank => true}, {:class => "form-control"} %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Procesar Pensum", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pensums/edit.html.erb
<h1>Editing Pensum</h1>

<%= render 'form', pensum: @pensum %>

<%= link_to 'Ver', @pensum %> |
<%= link_to 'Volver', pensums_path %>

app/views/pensums/index.html.erb
<h1>Pensums</h1>

<br>

<%= search_form_for @search do |f| %>
  <div class="form-inline">
    <div class='field'>
      <%= f.label :nombre_cont, "Nombre contiene:" %>
      <%= f.text_field :nombre_cont, class: "form-control" %>
      <input class="btn btn-primary" type="submit" value="Buscar">
    </div>
  </div>
<% end %>

<br>

<table class='table table-hover'>
  <thead>
    <tr>
      <th><%= sort_link @search, :universidad_id, "Universidad" %></th>
      <th><%= sort_link @search, :carrera_id, "Carrera" %></th>
      <th><%= sort_link @search, :nombre, "Nombre" %></th>
      <th><%= sort_link @search, :date, "Fecha" %></th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @pensums.each do |pensum| %>
      <tr>
        <td><%= pensum.carrera.universidad.nombre %></td>
        <td><%= pensum.carrera.nombre %></td>
        <td><%= pensum.nombre %></td>
        <td><%= pensum.date %></td>
        <td><%= link_to 'Ver', pensum %></td>
        <td><%= link_to 'Editar', edit_pensum_path(pensum) %></td>
        <td><%= link_to 'Borrar', pensum, method: :delete, data: { confirm: '¿Está Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Pensum', new_pensum_path %>

app/views/pensums/new.html.erb
<h1>Nuevo Pensum</h1>

<%= render 'form', pensum: @pensum %>

<%= link_to 'Volver', pensums_path %>

app/views/pensums/show.html.erb
<br><br>

<p>
  <strong>Nombre:</strong>
  <%= @pensum.nombre %>
</p>

<p>
  <strong>Date:</strong>
  <%= @pensum.date %>
</p>

<p>
  <strong>Universidad:</strong>
  <%= @pensum.carrera.universidad.nombre %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @pensum.carrera.nombre %>
</p>

<%= link_to 'Editar', edit_pensum_path(@pensum) %> |
<%= link_to 'Volver', pensums_path %>


<div id='info_tables_asignaturas_id'>
  <h3>Asignaturas</h3>

  <table class='table table-hover'>
    <thead>
      <tr>
        <th>Clave</th>
        <th>Nombre</th>
        <th>Creditos</th>
        <th>Universidad</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pensum.asignaturas.each do |asignatura| %>
        <tr>
          <td><%= asignatura.clave %></td>
          <td><%= asignatura.nombre %></td>
          <td><%= asignatura.creditos %></td>
          <td><%= asignatura.pensum.carrera.universidad.descripcion %> (<%= asignatura.pensum.carrera.universidad.nombre %>)</td>
          <td><%= link_to 'Ver', asignatura %></td>
          <td><%= link_to 'Editar', edit_asignatura_path(asignatura) %></td>
          <td><%= link_to 'Eliminar', asignatura, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>